name: Update GitHub Profile Graphs

on:
  schedule:
    - cron: '* * * * *'  # Schedule it to run every minute

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Choose your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python codeforces.py  # Replace with your Python script filename

      - name: Commit and push changes
        run: |
          git config user.name 'CoderInTheNorth-049'
          git config user.email 'amnetwork049@gmail.com'
          git add .
          git commit -m 'Update graphs'
          git push https://${{ secrets.GH_PAT }}@github.com/CoderInTheNorth-049/Codeforces_Tracker.git
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
